os:
  - linux

dist: groovy
language: cpp

# Compiler selection
compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-10
      - g++-10
      - cmake

# Build steps
script:
  - gcc -v && g++ -v && cmake --version
  - export CC=gcc-10
  - export CXX=g++-10
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
